// test curriculumn api

@path = http://env-1851196.proen.app.ruk-com.cloud/curriculums
@mytoken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJpYXQiOjE3MzgxMjg1MTYsImV4cCI6MTczODE3MTcxNn0.gRnd4Ifn6Ty2arequ-YumPpsrJ6BBQPDdFm7V5A78Z8


###

// Get curriculums
GET {{path}}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJpYXQiOjE3MzgxMjg1MTYsImV4cCI6MTczODE3MTcxNn0.gRnd4Ifn6Ty2arequ-YumPpsrJ6BBQPDdFm7V5A78Z8
Content-Type: application/json


// get curriculums by id
###
get {{path}}/25480191107226
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJpYXQiOjE3MzgxMjg1MTYsImV4cCI6MTczODE3MTcxNn0.gRnd4Ifn6Ty2arequ-YumPpsrJ6BBQPDdFm7V5A78Z8
Content-Type: application/json


// create user
###
post {{path}} HTTP/1.1
content-type: application/json

{
    "name": "Jelaludin joko",
    "position": "CEO",
    "contact": "1234567890",
    "email": "jelaludinjoko@gmail.com",
    "role": "Admin"

}

###
put {{path}}/1 HTTP/1.1
content-type: application/json

{
    "name": "John Doe update 1",
    "role": "Admin"
}


// delete user by id
###
delete {{path}}/1


/// give me random user json to create ////

//

{
    "name": "naruto Uzumaki",
    "position": "CEO",
    "contact": "1234567890",
    "email": "narutoUzumaki@gmail.com",
    "role": "Admin"
}

// user 2

{
    "name": "sasuke Uchiha",
    "position": "CEO",
    "contact": "1234567890",
    "email": "sasukeUchiha@gmail.com",
    "role": "Admin"
}

// user 3

{
    "name": "itachi Uchiha",
    "position": "CEO",
    "contact": "1234567890",
    "email": "itachiUchiha@gmail.com",
    "role": "Admin"
}
